Add Zcash Node
akash-network/awesome-akash pull request #313
Opened 2022-08-23 12:05 UTC by nfl0

Example SDL for running Zcash Node on Zcash mainnet

2023-04-08 18:02 UTC, andy108369 commented
@nfl0 thank you for your PR!
Please update the root level README.md before we can merge it.

2023-04-08 22:30 UTC, nfl0 commented
Thanks for your feedback! I've made the necessary changes and believe the code is now ready for merge. Please let me know if there's anything else that needs to be addressed before we proceed.

2023-04-12 12:42 UTC, andy108369 commented
@nfl0 looks great! Please add the last bit - `signedBy` attributes, e.g. https://github.com/akash-network/awesome-akash/blob/b720cd5/MySQL/deploy.yaml#L29-L32 to your deployment SDL manifest.

Thank you!

2023-04-12 15:02 UTC, andy108369 requested changes

2023-04-12 15:02 UTC, andy108369 commented on README.md
> +- [Zcash Node](zcashnode)
Please rename "zcashnode" to "Zcash" or other way around so it matches the directory you are adding ("Zcash" directory)

2023-04-12 15:46 UTC, andy108369 requested changes

2024-01-26 13:25 UTC, Dimokus88 commented on Zcash/start.sh
Hey @nfl0  !
You can look to the recommendation @andy108369 and resolve the branch conflict  ?

2024-02-02 02:44 UTC, AlirezaDarbandi commented
> Example SDL for running Zcash Node on Zcash mainnet

2024-02-26 18:01 UTC, Dimokus88 commented
Hey @nfl0 !
Need resolve branch conflict, for merge.

2024-02-27 04:36 UTC, nfl0 commented
Thank you for bringing the issue to my attention. I am currently working on resolving it.

2024-03-03 22:20 UTC, nfl0 commented on Zcash/start.sh
Converted, see Dockerfile, thanks for recommendations.

2024-03-05 01:43 UTC, nfl0 commented
@Dimokus88 done

2024-10-13 12:32 UTC, nfl0 commented
I'm closing this PR as zcashd will be deprecated in the next few months and replaced by the Zcash Zebrad software, which is already in production: [Zebra](https://github.com/ZcashFoundation/zebra).

2024-10-13 12:33 UTC, closed without merging